name: Build AMI

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  build-ami:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Packer
      uses: hashicorp/setup-packer@v3

    - name: Initialize Packer
      run: packer init ./packer/aws.pkr.hcl

    - name: Build AMI
      env:
        AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        packer build \
          -var "aws_source_ami=${AWS_SOURCE_AMI}" \
          -var "db_user=${DB_USER}" \
          -var "db_password=${DB_PASSWORD}" \
          -var "dockerhub_username=${DOCKERHUB_USERNAME}" \
          -var "dockerhub_token=${DOCKERHUB_TOKEN}" \
          ./packer/ami.pkr.hcl
