name: Build and Deploy

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/trading-service

on:
  push:
    branches: [ main ]

jobs:
  build-image:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  build-ami:
    name: "Build AMI"
    runs-on: ubuntu-latest
    needs: build-image

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Packer
      uses: hashicorp/setup-packer@v3

    - name: Initialize Packer
      run: packer init ./packer/ami.pkr.hcl

    - name: Build AMI
      env:
        AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        packer build \
          -var "aws_source_ami=${AWS_SOURCE_AMI}" \
          -var "db_user=${DB_USER}" \
          -var "db_password=${DB_PASSWORD}" \
          -var "docker_username=${DOCKER_USERNAME}" \
          -var "docker_token=${DOCKER_TOKEN}" \
          ./packer/ami.pkr.hcl
