name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_check:
    name: "Packer Format and Validation Check"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Packer
      uses: hashicorp/setup-packer@v3

    - name: Initialize Packer
      run: packer init ./packer/ami.pkr.hcl

    - name: Run Packer Fmt
      run: packer fmt -check -diff ./packer/ami.pkr.hcl

    - name: Run Packer Validate
      env:
        AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        packer validate \
          -var "aws_source_ami=${AWS_SOURCE_AMI}" \
          -var "db_user=${DB_USER}" \
          -var "db_password=${DB_PASSWORD}" \
          -var "docker_username=${DOCKER_USERNAME}" \
          -var "docker_token=${DOCKER_TOKEN}" \
          ./packer/ami.pkr.hcl